### ISSUE TITLE
Build Ports - TypeError: unsupported type: <class 'NoneType'>

### ISSUE THREAD

**Issue by pagalba-com** [USBToolBox/kext#6]
Using v1.1, port detection works, settings type for selected ports, and choosing build 'K' result in error:

  #######################################################
 #                  Building USBMap                    #
#######################################################

Generating Info.plist...
Writing kext and Info.plist...
Traceback (most recent call last):
  File "macOS.py", line 174, in <module>
  File "base.py", line 49, in __init__
  File "base.py", line 679, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 362, in select_ports
  File "base.py", line 623, in build_kext
  File "plistlib.py", line 894, in dump
  File "plistlib.py", line 325, in write
  File "plistlib.py", line 348, in write_value
  File "plistlib.py", line 389, in write_dict
  File "plistlib.py", line 348, in write_value
  File "plistlib.py", line 389, in write_dict
  File "plistlib.py", line 348, in write_value
  File "plistlib.py", line 389, in write_dict
  File "plistlib.py", line 348, in write_value
  File "plistlib.py", line 389, in write_dict
  File "plistlib.py", line 348, in write_value
  File "plistlib.py", line 389, in write_dict
  File "plistlib.py", line 348, in write_value
  File "plistlib.py", line 389, in write_dict
  File "plistlib.py", line 360, in write_value
TypeError: unsupported type: <class 'NoneType'>
[1925] Failed to execute script macOS

**Comment by pagalba-com** [comment]
even set type for unpopulated/unused ports, this didn't help.
there is one internal type port 255, disabling that one, didn't help.
